=== juh9870/random_cli/spm/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Config",
  "type": "object",
  "required": [
    "default_profile",
    "environments",
    "preprocessors",
    "profiles",
    "runners"
  ],
  "properties": {
    "$schema": {
      "type": [
        "string",
        "null"
      ]
    },
    "default_profile": {
      "type": "string"
    },
    "environments": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/GlobEntry_for_ProjectEnv"
      }
    },
    "preprocessors": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Preprocessor"
      }
    },
    "profiles": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/Profile"
      }
    },
    "runners": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/GlobEntry_for_IdeRunner"
      }
    }
  },
  "definitions": {
    "GlobEntry_for_IdeRunner": {
      "type": "object",
      "required": [
        "binary",
        "command",
        "glob"
      ],
      "properties": {
        "binary": {
          "description": "Binary that is used to run the project",
          "type": "string"
        },
        "command": {
          "description": "Format string to generate run command",
          "type": "string"
        },
        "glob": {
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "null"
          ]
        },
        "nix_package": {
          "description": "Nix package to install if the runner is missing in path",
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "GlobEntry_for_ProjectEnv": {
      "description": "Environment the project is running in",
      "type": "object",
      "required": [
        "command",
        "glob",
        "ide_command"
      ],
      "properties": {
        "command": {
          "description": "Format string to generate run command",
          "type": "string"
        },
        "glob": {
          "type": "string"
        },
        "ide_command": {
          "description": "Format string to generate run command",
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "null"
          ]
        },
        "nix_template": {
          "description": "Template file for this environment",
          "anyOf": [
            {
              "$ref": "#/definitions/NixTemplate"
            },
            {
              "type": "null"
            }
          ]
        },
        "runner": {
          "description": "Runner that is used to run the IDE",
          "anyOf": [
            {
              "$ref": "#/definitions/IdeRunner"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    },
    "IdeRunner": {
      "type": "object",
      "required": [
        "binary",
        "command"
      ],
      "properties": {
        "binary": {
          "description": "Binary that is used to run the project",
          "type": "string"
        },
        "command": {
          "description": "Format string to generate run command",
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "null"
          ]
        },
        "nix_package": {
          "description": "Nix package to install if the runner is missing in path",
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "NixTemplate": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "Path"
          ],
          "properties": {
            "Path": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "Preprocessor": {
      "type": "object",
      "required": [
        "command",
        "glob",
        "name"
      ],
      "properties": {
        "command": {
          "type": "string"
        },
        "glob": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "Profile": {
      "type": "object",
      "required": [
        "projects"
      ],
      "properties": {
        "projects": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Project"
          }
        }
      }
    },
    "Project": {
      "type": "object",
      "required": [
        "name",
        "path"
      ],
      "properties": {
        "environment": {
          "anyOf": [
            {
              "$ref": "#/definitions/ProjectEnv"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "runner": {
          "anyOf": [
            {
              "$ref": "#/definitions/IdeRunner"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    },
    "ProjectEnv": {
      "description": "Environment the project is running in",
      "type": "object",
      "required": [
        "command",
        "ide_command"
      ],
      "properties": {
        "command": {
          "description": "Format string to generate run command",
          "type": "string"
        },
        "ide_command": {
          "description": "Format string to generate run command",
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "null"
          ]
        },
        "nix_template": {
          "description": "Template file for this environment",
          "anyOf": [
            {
              "$ref": "#/definitions/NixTemplate"
            },
            {
              "type": "null"
            }
          ]
        },
        "runner": {
          "description": "Runner that is used to run the IDE",
          "anyOf": [
            {
              "$ref": "#/definitions/IdeRunner"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    }
  }
}

=== juh9870/random_cli/spm/src/default_config.json
{
  "$schema": null,
  "default_profile": "default",
  "profiles": {
    "default": {
      "projects": []
    }
  },
  "environments": [
    {
      "glob": "/shell.nix",
      "name": "nix shell",
      "command": "nix-shell {path}/shell.nix",
      "ide_command": "nix-shell {path}/shell.nix --run {ide}"
    },
    {
      "glob": "/flake.nix",
      "name": "nix flake",
      "command": "nix develop",
      "ide_command": "nix develop --command {ide}"
    },
    {
      "glob": "*",
      "name": "plain shell",
      "command": "bash",
      "ide_command": "bash -c {ide}"
    }
  ],
  "runners": [
    {
      "glob": "/Cargo.toml",
      "name": "clion",
      "binary": "clion",
      "nix_package": "jetbrains.clion",
      "command": "clion {path}"
    },
    {
      "glob": "/package.json",
      "name": "webstorm",
      "binary": "webstorm",
      "nix_package": "jetbrains.webstorm",
      "command": "webstorm {path}"
    },
    {
      "glob": "/go.mod",
      "name": "goland",
      "binary": "goland",
      "nix_package": "jetbrains.goland",
      "command": "goland {path}"
    },
    {
      "glob": "/*.csproj",
      "name": "rider",
      "binary": "rider",
      "nix_package": "jetbrains.rider",
      "command": "rider {path}"
    },
    {
      "glob": "*",
      "name": "codium",
      "binary": "codium",
      "nix_package": "vscodium",
      "command": "vscodium {path}"
    }
  ],
  "preprocessors": [
    {
      "name": "cargo2nix",
      "glob": "./Cargo.nix",
      "command": "nix run github:cargo2nix/cargo2nix -- -o"
    }
  ]
}
